version: '3.8'  # Using a more current version for better feature support
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: ${COMPOSE_PROJECT_NAME:-taco}_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: ${COMPOSE_PROJECT_NAME:-taco}_kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    container_name: ${COMPOSE_PROJECT_NAME:-taco}_filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - elasticsearch
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME:-taco}_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    depends_on:
      - web
    ports:
      - "8080:80"
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-taco}_web
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  elasticsearch-data:
  nginx-logs:
